[[bond]]
source = "tpknam1qruavm6j82kfw5ffp7rq9k8c5ay5xdppssx07alcsvsjww7z3nvdqqjjcgc"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "800"

[bond.signatures]
tpknam1qruavm6j82kfw5ffp7rq9k8c5ay5xdppssx07alcsvsjww7z3nvdqqjjcgc = "signam1qpqmrmusdvsm3g5a7r0dq9jfkew90qx0nsgfchchez27a5sgt9k0xtnzlcjle9xh773guhzamyhc22ewmug7ytp4jdsn9sjy46rfj2gyc58w79"
